spring:
  application:
    name: CONFIG-CLIENT

# eureka client discovery configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true # by default true
    service-url:
      defaultZone: http://localhost:8765/eureka

